apiVersion: v1
kind: Template
metadata:
  name: lgen
parameters:
  - description: The name of the image to use
    name: IMAGE_NAME
    value: pilhuhn/lgen
objects:
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: lgen-hosa-map
    labels:
      app: lgen
  data:
    hawkular-openshift-agent: |
      endpoints:
      - type: prometheus
        collection_interval_secs: 60
        protocol: "http"
        port: 8080
        path: /metrics
        tags:
          name: ${POD:label[project]}
        metrics:
        - name: metric_without_timestamp_and_labels
          type: gauge
        - name: metric_without_timestamp_and_labels2
        - name: metric_with_label
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: lgen-is
    labels:
      app: lgen
  spec:
    dockerImageRepository: ${IMAGE_NAME}:latest
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: lgen
      project: lgen
    name: lgen
  spec:
    replicas: 1
    selector:
      app: lgen
      deploymentconfig: lgen
    strategy:
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          app: lgen
          deploymentconfig: lgen
          project: lgen
      spec:
        volumes:
          - name: hawkular-openshift-agent
            configMap:
              name: lgen-hosa-map
        containers:
        - image: ${IMAGE_NAME}
          imagePullPolicy: Always
          name: lgen
          ports:
          - containerPort: 8080
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        securityContext: {}
        terminationGracePeriodSeconds: 30
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - lgen
        from:
          kind: ImageStreamTag
          name: lgen-is:latest
      type: ImageChange
- apiVersion: v1
  kind: Service
  metadata:
    name: lgen
    labels:
      app: lgen
  spec:
    ports:
      - protocol: TCP
        port: 8080
    selector:
      app: lgen